eureka:
  client:
    service-url:
      defaultZone: http://registry.zhengshi.tech:8761/eureka
    prefer-same-zone-eureka: true
  instance:
    prefer-ip-address: true

spring:
  cloud:
    config:
      uri:  http://config.zhengshi.tech:8888
      env:  default
      label: master
      name: web-service-subject

words: You,I,He
