server:
  port: 8020

spring:
  application:
    name: zhengshitech-eureka-sentence-server

eureka:
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
            defaultZone: http://localhost:8888/eureka