eureka:
  client:
    service-url:
      defaultZone: http://registry.zhengshi.tech:8761/eureka
    prefer-same-zone-eureka: true
  instance:
    prefer-ip-address: true


info:
  component: dash board

server:
  port: 2018

spring:
  application:
    name: dash-board-server
