eureka:
  client:
    service-url:
      defaultZone: http://registry.zhengshi.tech:8761/eureka
    prefer-same-zone-eureka: true
  instance:
    prefer-ip-address: true


server:
  port: 5555

spring:
  application:
    name: gateway-server