eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
  # Allow Eureka to recognize two apps of the same type on the same host as separate instances:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

actioins: Eating,Dancing,Gaming

server:
  port: ${PORT:${SERVER_PORT:0}}
#  这个的意思是随机指定个没使用的端口